[package]
name = "firefly-io"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.2.0"
esp-backtrace = { version = "0.14.2", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
embedded-hal = { version = "1.0.0" }
embedded-hal-bus = "0.2.0"
esp-alloc = { version = "0.5.0" }
esp-hal = { version = "0.22.0", features = ["esp32s3"] }
esp-println = { version = "0.12.0", features = ["esp32s3"] }
esp-wifi = { version = "0.11.0", features = ["esp32s3", "esp-now"] }
firefly-hal = { path = "../firefly-hal" }
firefly-types = { version = "0.4.0", path = "../firefly-types" }
cirque-pinnacle = "1.0.0"
