[package]
name = "firefly-io"
version = "0.1.0"
edition = "2021"
rust-version = "1.88.0"

[dependencies]
critical-section = "1.2.0"
esp-backtrace = { version = "0.18.1", features = [
    "esp32s3",
    "panic-handler",
    "println",
] }
embedded-hal = { version = "1.0.0" }
embedded-hal-bus = "0.3.0"
embedded-io = { version = "0.6.1", default-features = false }
esp-alloc = { version = "0.8.0" }
esp-hal = { version = "1.0.0-rc.0", features = ["esp32s3", "unstable"] }
esp-println = { version = "0.16.1", features = ["esp32s3"] }
esp-wifi = { version = "0.15.0", features = ["esp32s3", "esp-now"] }
esp-wifi-sys = "0.7.1"
firefly-types = { version = "0.6.1" }
cirque-pinnacle = "1.0.1"
portable-atomic = "1.11.1"

[profile.release]
strip = true             # Automatically strip symbols from the binary.
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "z"          # Optimize for size.
overflow-checks = false
panic = "abort"
