[package]
name = "firefly-net"
version = "0.1.0"
edition = "2021"

[dependencies]
firefly-hal = { path = "../firefly-hal" }
esp-backtrace = { version = "0.14.2", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.22.0", features = ["esp32s3"] }
esp-println = { version = "0.12.0", features = ["esp32s3"] }
esp-alloc = { version = "0.5.0" }
critical-section = "1.2.0"
embedded-hal-bus = "0.2.0"
esp-wifi = { version = "0.11.0", features = ["esp32s3", "esp-now"] }
heapless = "0.8.0"
